include:
  - '/ci/yocto-ktn-build.yml'
  - '/ci/container-build.yml'

stages:
  - build-container
  - build

# Build Yocto BSPs
bsp-mx8mm:build:
  extends: .yocto-build-template
  variables:
    KAS_CONFIG: kas/ktn-mx8mm.yml

bsp-mx6ul:build:
  extends: .yocto-build-template
  variables:
    KAS_CONFIG: kas/ktn-mx6ul.yml

bsp-mp1:build:
  extends: .yocto-build-template
  variables:
    KAS_CONFIG: kas/ktn-mp1.yml

# Build Container Image
.container-vars: &container-vars
  variables:
    CONTAINERFILE: Containerfile
    TAG: kas-ktn

container:build:
  extends: .build-container
  <<: *container-vars

container:build-deploy:
  extends: .build-deploy-container
  <<: *container-vars
