include:
  - '/ci/yocto-ktn-build.yml'
  - '/ci/container-build.yml'

stages:
  - build-container
  - build

# Build Yocto BSPs
.build-matrix: &build-matrix
  - KAS_CONFIG: kas/ktn-mx8mm.yml
  - KAS_CONFIG: kas/ktn-mx6ul.yml
  - KAS_CONFIG: kas/ktn-mp1.yml

build:
  extends: .build-config
  parallel:
    matrix:
      *build-matrix

# Build Container Image
.container-vars: &container-vars
  variables:
    CONTAINERFILE: Containerfile
    TAG: kas-ktn

container:build:
  extends: .build-container
  <<: *container-vars

container:build-deploy:
  extends: .build-deploy-container
  <<: *container-vars
