include:
  - '/ci/yocto-ktn-build.yml'
  - '/ci/container-build.yml'

stages:
  - build-container
  - build

# Build Yocto BSPs
.build-matrix: &build-matrix
  - PLATFORM: mx8mm
    YOCTO_SERIES: dunfell
  - PLATFORM: mx6ul
    YOCTO_SERIES: dunfell
  - PLATFORM: mp1
    YOCTO_SERIES: dunfell

bsp:build:
  extends: .yocto-build-template
  parallel:
    matrix:
      *build-matrix
  variables:
    KAS_CONFIG: "kas/ktn-${PLATFORM}.yml:kas/series/${YOCTO_SERIES}.yml"
  rules:
    - if: $HEAD_BUILD == "1"
      variables:
        KAS_CONFIG: "${KAS_CONFIG}:kas/dev/head.yml"
    - when: always

# Build Container Image
.container-vars: &container-vars
  variables:
    CONTAINERFILE: Containerfile
    TAG: kas-ktn

container:build:
  extends: .build-container
  <<: *container-vars

container:build-deploy:
  extends: .build-deploy-container
  <<: *container-vars
