include:
  - '/ci/inc/build.yml'

.build-matrix: &build-matrix
  - PLATFORM: mx8mm
    YOCTO_SERIES: dunfell
    TARGETS: "image-ked-qt"
  - PLATFORM: mx6ul
    YOCTO_SERIES: dunfell
    TARGETS: "image-ked"
  - PLATFORM: mp1
    YOCTO_SERIES: dunfell
    TARGETS: "image-ked"
  - PLATFORM: mx8mm
    YOCTO_SERIES: kirkstone
    TARGETS: "image-ked-qt"
  - PLATFORM: mx8mp
    YOCTO_SERIES: kirkstone
    TARGETS: "image-ked-qt"
  - PLATFORM: mx6ul
    YOCTO_SERIES: kirkstone
    TARGETS: "image-ked-qt"
  - PLATFORM: mp1
    YOCTO_SERIES: kirkstone
    TARGETS: "image-ked"

.common-vars: &common-vars
  KAS_CONFIG: "kas/ked-${PLATFORM}.yml:kas/series/${YOCTO_SERIES}.yml"
  KAS_CONFIG_HEAD: "kas/dev/head-${YOCTO_SERIES}.yml"
  BUILD_NAME: "${PLATFORM}-${YOCTO_SERIES}"

bsp:build:
  extends: .yocto-build-template
  parallel:
    matrix:
      *build-matrix
  variables:
    *common-vars

bsp:build:release:
  extends: .yocto-build-release-template
  parallel:
    matrix:
      *build-matrix
  variables:
    *common-vars
